### ISSUE TITLE
Webpack inline no longer works after initial compile.

### ISSUE THREAD

**Issue by haroldiedema** [hostnet/webpack-bundle#30] opened 2015-11-27 09:37 UTC
The compiled source is no longer included when using the `inline`-tag after modifying the inline code and doing a page reload.

```javascript
{% webpack inline js %}
var graph = require('@SomeBundle/Graph.jsx'); 
console.log(graph);
{% endwebpack %}
```

The above works initially on a clean cache. After modifying the inline code (e.g. adding a new line or whatever), the script-tag including the compiled code is no longer included in the template.

The file compiles correctly though and shows up in the compile output in the profiler.

**Comment by iltar** [comment] 2015-11-27 15:19
I was unable to reproduce this issue but I haven't tried it with a jsx.

**Comment by haroldiedema** [comment] 2015-11-27 16:23
If it works in "main" templates, try to do ti in an included template.

**Comment by iltar** [comment] 2015-11-27 19:14
I've tested that case, the only time it broke (completely, all js/css) was when I put it outside of a block tag in a template. Have not been able to reproduce this specific case you mentioned. I can imagine the hash changing and not having the right permissions to update it in `/web/compiled` though, I had a lot of issues with that as well.

**Comment by iltar** [comment] 2016-02-12 14:20
Closing this issue as I cannot reproduce it

**Closed by iltar** 2016-02-12 14:20 UTC
Labels: bug
